<div class="container-fluid main_div">

<div class="inside_main">

<div class="container-fluid">
  <div class="row1 container_small">

    <div class="item item_margin">
      <div class="inline_block margin_top">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/cetvorta_slika.jpg'); ?>"  />
      </div>
        <div class="inline_block">
      </div>
    </div>

    <div class="vertical_top_line"></div>

    <div class="item item_margin margin_top">
      <div class="inline_block">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/treta_slika.jpg'); ?>"  />
      </div>
      <div class="inline_block">
        <p class="red_text">Checkout</p>
      </div>
    </div>

    <div class="item item_margin margin_top">
      <div class="inline_block">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/vtora_slika.jpg'); ?>"  />
      </div>
      <div class="inline_block">
        <p class="red_text">Chart</p>
      </div>
    </div>

    <div class="item item_margin margin_top">
      <div class="inline_block">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/prva_slika.jpg'); ?>"  />
      </div>
      <div class="inline_block">
        <p class="red_text">My account</p>
      </div>
    </div>

  </div>
</div> 

<div class="container-fluid"> 
  <div class="row1">
    <div class="horizontal_line"></div>
  </div>
</div>

<div class="container-fluid">
  <div class="row2 container_small">
    <div class="item item_margin">
      <div class="block_style expand_image">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/number4.jpg'); ?>"  />
      </div>
      <div class="block_style">
        <p class="white_text">MY CHART</p>
      </div>
    </div>

    <div class="vertical_line"></div>

    <div class="item item_margin">
      <div class="block_style expand_image">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/number3.jpg'); ?>"  />
      </div>
      <div class="block_style">
        <div class="white_text">COMPARE</div>
      </div>
    </div>

    <div class="vertical_line"></div>

    <div class="item item_margin">
      <div class="block_style expand_image">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/number2.jpg'); ?>"  />
      </div>
      <div class="block_style">
        <p class="white_text">WISHLIST</p>
      </div>
    </div>

    <div class="vertical_line"></div>

    <div class="item flex_growing item_contact">
      <div class="block_right">
        <div class="only_inline">
          <div class="item_picture">
          <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/number1.jpg'); ?>"  />
          </div>
        </div>
        <p class="only_inline white_text font_size text_margin_top">+0123 456 789</p>
      </div>
      <p class="block_right text_color text_center" style="font-size: 10px;"><span class="blok">MON-FRI: 8:30AM-7:30PM;  </span><span>SAT-SUN:9:30AM-4:30PM</span></p>
    </div>

    <div class="item flex_growing">
      <div class="text_left">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/slika5.jpg'); ?>"  />
      </div>
    </div>

  </div>
</div>

</div>

</div>


<div class="div_menu">
  <div class="container_style white_text">
    <div class="div_home div_margin_top">HOME</div>
    <div class="div_each div_margin_top">SERVICES</div>
    <div class="div_each div_margin_top">ABOUT</div>
    <div class="div_each div_margin_top">REVIEWS</div>
    <div class="div_each div_margin_top">LOCATIONS</div>
    <div class="div_each div_margin_top">CONTACTS</div>
  </div>
</div>


<img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/image1.jpg'); ?>"  /> 


<div class="images_row">
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/x11.jpg'); ?>" /> </div>
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/x22.jpg'); ?>" /> </div>
</div>
<div class="images_row">
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/x33.jpg'); ?>"  /> </div>
    <div class="one_image"><img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/x44.jpg'); ?>"  /> </div>
</div>


<img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/slikaslika2.jpg'); ?>"  />
